### ISSUE TITLE
Initial Styles doesn't work

### ISSUE THREAD

**Issue by shakogegia** [imnapo/react-native-cn-richtext-editor#54] opened 2019-04-24 17:33 UTC
Hi, I can not make styles work

```
this.state.value = convertToObject(html)
```

this not works, editor does not getting styles from html

however, if user edits text than styles are working fine,
but cant make initial styles work

`html` is like
```html
<div><p><span style="font-weight: bold">This should be a bold text</span></p></div>
```
and `convertToObject(html)` not attaching styles to it :(

![Alt Text](https://media.giphy.com/media/dAKEM3bEId9JlGqzGC/giphy.gif)

**Comment by imnapo** [comment] 2019-04-25 06:40
Hi @shakogegia , you are missing a semicolon ( ; ) after _font-weight: bold_ . Your html string should be like this: 
`<div><p><span style="font-weight: bold;">This should be a bold text</span></p></div>`

**Comment by imnapo** [comment] 2019-05-03 10:08
I’m going to close this for now. Feel free to reopen, if the problem is not solved.

**Closed by imnapo** 2019-05-03 10:08 UTC
