### ISSUE TITLE
[Question] Suggestions on how to save to db the content with images

### ISSUE THREAD

**Issue by koo27** [imnapo/react-native-cn-richtext-editor#51] opened 2019-04-10 15:31 UTC
I'd like to save to database (mongodb) the content of the text editor with images.
Using the `convertToHtmlString` method it converts the whole document in html, using file:// for the images.
Do you have any idea on how to save the images in order to retrieve them later and convert it back to Object (using the `convertToObject` method) and let the user edit the document again?
Should I have to save the images separately, edit the html keeping track of the new images url?

**Comment by imnapo** [comment] 2019-04-12 18:49
Yes, You should save images separately to your storage first then pass download URL to the editor instead of local file name.

**Comment by imnapo** [comment] 2019-05-03 10:07
I’m going to close this for now. Feel free to reopen, if the problem is not solved.

**Closed by imnapo** 2019-05-03 10:07 UTC

**Comment by koo27** [comment] 2019-05-03 10:46
I'm sorry for my late reply, I actually didn't see your answer.
Can you be so kind to send the sample code of what you did?

Thank you very much

**Comment by himanshupadia** [comment] 2020-06-23 11:22
@koo27 @imnapo could you please help me get value from editer with HTML tags so I can sent it to db with same? I am stuck add looking for solution from last 2 days. Please help me.
appreciating your help, because of this only I got stuck. 
**Input String:** This is **bold** and _italic_ text
**output should be something like this or in format of editor:** 
`<div><p><span>This is </span><span style="font-weight: bold;">bold</span><span> and </span><span style="font-style: italic;">italic </span><span>text</span></p></div>`

**Comment by koo27** [comment] 2020-06-23 12:04
It's been very long time, anyway if I'm not wrong, you should just save the "value" of the editor in a state, convert it to HTML and then send it to your api (to save it to your db).
I used a FormData to send images too.

So let's assume this.state.value is the value of the editor


```javascript
<CNRichTextEditor
   ref={input => this.editor = input}
   onSelectedTagChanged={this.onSelectedTagChanged}
   onSelectedStyleChanged={this.onSelectedStyleChanged}
   value={this.state.value}
   style={styles.editor}
   styleList={defaultStyles}
   foreColor='dimgray' // optional (will override default fore-color)
   onValueChanged={this.onValueChanged}
   onRemoveImage={this.onRemoveImage}
/>
```

Then convert the value in HTML with convertToHtmlString
```javascript
let html = convertToHtmlString(this.state.value)
```

Then send it to your db. As I said I used a formData for the images.
A simple example could be:

```javascript
           let html = convertToHtmlString(this.state.value)
            var image = ''

            if (this.state.article.image.mime !== '')
                image = {
                    uri: this.state.article.image.path,
                    type: this.state.article.image.mime,
                    name: this.state.article.image.name
                }

            let body = new FormData();

            body.append('title', this.state.article.title)
            body.append('content', html)
            body.append('image', image)

            this.props.post(body, ID)
```

**Comment by himanshupadia** [comment] 2020-06-25 15:12
@koo27 thank you very very much.
