### ISSUE TITLE
Cursor of TextInput auto jumping crazy after input text on Android with RN 0.60.3

### ISSUE THREAD

**Issue by asiadigitalhub** [imnapo/react-native-cn-richtext-editor#70] opened 2019-08-01 03:26 UTC
Thanks for this helpful lib. It already working fine with me on RN 0.57.3 but after I update version, this bug is appear. I already debug many times, maybe relate to TextInput on CNTextInput. The onSelectionChange call twice time every type any text input and return  different selection value.

**Comment by nishiltamboli** [comment] 2019-08-03 15:55
I can confirm I also face the same issue with RN 0.60+ version.

**Comment by rezaarifian** [comment] 2019-08-15 05:27
same issue on RN 0.60.4 

no pull request for next release

**Comment by dancomanlive** [comment] 2019-08-15 18:56
Same on 0.60.0. Any solution?

**Comment by imnapo** [comment] 2019-08-16 10:23
Hi guys, we are working on this issue and we will try to fix it as soon as possible.

**Comment by imnapo** [comment] 2019-08-29 14:21
It seems this issue is related to react-native TextInput Component.
You may follow related issues :  facebook/react-native#26047 and facebook/react-native#25265

**Comment by danilolucasmd** [comment] 2019-09-05 18:15
same issue on RN 0.59.8

**Comment by srhtylmz19** [comment] 2019-09-07 14:46
any update?

**Comment by ohpax** [comment] 2019-09-08 15:54
I am going to close this because as @imnapo said this issue is with react-native library.

**Closed by ohpax** 2019-09-08 15:54 UTC
Labels: bug

**Comment by srhtylmz19** [comment] 2019-09-08 16:11
its not related with react native , cus it works well with TextInput of react native

**Comment by sushantb21** [comment] 2019-10-16 13:06
Its not a bug there is a mistake in example code 

Example Code:
onValueChanged={this.onValueChanged}

Reproduced code:
onValueChanged={() => this.onValueChanged}

overall code in view

`<View style={{flex:1}}>
                    <KeyboardAvoidingView
                        behavior="padding"
                        enabled
                        keyboardVerticalOffset={0}
                        style={{
                            flex: 1,
                            paddingTop: 20,
                            backgroundColor:'#eee',
                            flexDirection: 'column',
                            justifyContent: 'flex-end',
                        }}
                    >
                        <TouchableWithoutFeedback onPress={Keyboard.dismiss} >
                            <View style={styles.main}>
                                <CNRichTextEditor
                                    ref={input => this.editor = input}
                                    onSelectedTagChanged={this.onSelectedTagChanged}
                                    onSelectedStyleChanged={this.onSelectedStyleChanged}
                                    value={this.state.value}
                                    style={{ backgroundColor : '#fff'}}
                                    styleList={defaultStyles}
                                    onValueChanged={() => this.onValueChanged}
                                />
                            </View>
                        </TouchableWithoutFeedback>

                        <View style={{
                            minHeight: 35
                        }}>

                            <CNToolbar
                                size={28}
                                bold={<Text style={[styles.toolbarButton, styles.boldButton]}>B</Text>}
                                italic={<Text style={[styles.toolbarButton, styles.italicButton]}>I</Text>}
                                underline={<Text style={[styles.toolbarButton, styles.underlineButton]}>U</Text>}
                                lineThrough={<Text style={[styles.toolbarButton, styles.lineThroughButton]}>S</Text>}
                                body={<Text style={styles.toolbarButton}>T</Text>}
                                title={<Text style={styles.toolbarButton}>h1</Text>}
                                heading={<Text style={styles.toolbarButton}>h3</Text>}
                                ul={<Text style={styles.toolbarButton}>ul</Text>}
                                ol={<Text style={styles.toolbarButton}>ol</Text>}

                                selectedTag={this.state.selectedTag}
                                selectedStyles={this.state.selectedStyles}
                                onStyleKeyPress={this.onStyleKeyPress} />
                        </View>
                    </KeyboardAvoidingView>
                </View>`

**Comment by sushantb21** [comment] 2019-10-16 13:40
use this code 
<CNRichTextEditor
                                    ref={input => this.editor = input}
                                    onSelectedTagChanged={() => this.onSelectedTagChanged}
                                    onSelectedStyleChanged={() => this.onSelectedStyleChanged}
                                    value={this.state.value}
                                    style={{ backgroundColor : '#fff'}}
                                    styleList={defaultStyles}
                                    onValueChanged={() => this.onValueChanged}
                                />

**Comment by hussainhspl** [comment] 2020-03-20 09:53
> use this code
> <CNRichTextEditor
> ref={input => this.editor = input}
> onSelectedTagChanged={**() => this.onSelectedTagChanged**}
> onSelectedStyleChanged={**() => this.onSelectedStyleChanged**}
> value={this.state.value}
> style={{ backgroundColor : '#fff'}}
> styleList={defaultStyles}
> onValueChanged={**() => this.onValueChanged**}
> />

making fat arrow function will solve the issue
