### ISSUE TITLE
How to change value programmatically

### ISSUE THREAD

**Issue by VivekSharma811** [imnapo/react-native-cn-richtext-editor#48] opened 2019-04-03 12:28 UTC
I am using react-native-cn-richtext-editor in my React Native app for Android. I am able to change the value of text input programmatically, but after value is updated on input field the value keeps repeating if i do any changes from UI(means even if i don't press submit button, pressSubmit is executing). I am pretty sure that i haven't done any mistake in calling the pressSubmit function. I also have tried the same using Modal(instead of Dialog), but that too didn't worked. I am sharing my code and versions i am using. Please tell me if my approach is correct or not. If not, then how can i make it work?

RN: 0.58.6
React: 16.6.3

pressSubmit = () => {
        console.log('pressSubmit reached');
        if(this.state.visible) {
            this.editor.textInputs[0].props.items[0].text = this.editor.textInputs[0].props.items[0].text  + ' : ' + this.state.modalValue;
        } else {
            this.editor.textInputs[0].props.items[0].text = this.editor.textInputs[0].props.items[0].text ;
        }
        this.setState({
            visible : false,
        });
}

render() {
return (
<Dialog.Container visible={this.state.visible}>
    <Dialog.Title>Add Concept</Dialog.Title>
    <Dialog.Input
    value={this.state.modalValue}
    onChangeText={(text) => this.setState({modalValue : text})}>
    </Dialog.Input>
    <Dialog.Button label="CANCEL" onPress={()=>{this.onCancelPress()}}/>
    <Dialog.Button label="SUBMIT" onPress={()=>{this.pressSubmit()}}/>
</Dialog.Container>
)
}

Thanks in advance.

**Comment by imnapo** [comment] 2019-04-03 21:13
Hi @VivekSharma811 , Adding any text or style pragmatically is not easy and we don't support it because the editor works also with other local variable to detect changes.
But if you want to just add a simple text (not included any newline char) to end of one of items like the example you sent.
`this.editor.textInputs[0].props.items[0].text = this.editor.textInputs[0].props.items[0].text + ' : ' + this.state.modalValue;`

try also change **len** property of javascript object like below, it may solve your problem

`this.editor.textInputs[0].props.items[0].len= this.editor.textInputs[0].props.items[0].len+ ' : ' + this.state.modalValue.length;`
let me know if this helps you or send us a simple demo of what you exactly want to do, so we can help you better.

**Comment by VivekSharma811** [comment] 2019-04-04 06:07
Hi @imnapo , above suggestion did not made a difference. The issue still persists.
What i intend to do is:
A dynamic list is loaded below the Input Field of the editor. When the user clicks on the list, a Dialog Box appears with a text input asking for the frequency. After the user clicks submit(from the Dialog Box), the Input Field should be updated with the value => {text present in the list clicked + ' : ' + value of text input from Dialog Box}
For ex. List has a value of 'Burger' and from Dialog Box, I select frequency of '5' and click submit.
Then the text field of editor should be updated to 'Burger : 5'
I am able to do this task, but right after this value gets updated to the editor's input field the editor becomes unusable. 
Using the above example again, after the text is updated to 'Burger : 5' and i click ' '(space),
the text updates to 'Burger : 5 Burger : 5'

Hope i am able to make you understand my problem.

**Comment by imnapo** [comment] 2019-04-12 18:28
Hi @VivekSharma811 , We are busy with adding typing support to this package , sorry for late answer.  
You may try this for now: 
`this.editor.textInputs[0].handleChangeText(this.editor.textInputs[0].oldText + 'Burger : 5');`
I tried this and its worked.
Be noticed that you should pass whole text ( existing + new one ) to this function: **handleChangeText**  and you may find existing text with `this.editor.textInputs[0].oldText` 
We will provide a better way in future releases for sure.

**Comment by imnapo** [comment] 2019-05-03 10:06
I’m going to close this for now. Feel free to reopen, if the problem is not solved.

**Closed by imnapo** 2019-05-03 10:06 UTC
