### ISSUE TITLE
CNRichTextView  scroll for long text does not work

### ISSUE THREAD

**Issue by orhanoksuzz** [imnapo/react-native-cn-richtext-editor#59] opened 2019-05-14 03:56 UTC
Hi, When I wanted to see the data that I saved with the Editor, I found that the scroll is not active.

The platform I use is IOS

Result 
![ezgif-1-83ad35520f7d](https://user-images.githubusercontent.com/16277060/57669826-542ae980-7615-11e9-8ac8-1e358aecdbd1.gif)

Updated

![ezgif-1-53ccf061084e](https://user-images.githubusercontent.com/16277060/57719554-abb66d00-7688-11e9-8d6c-70631145d757.gif)

**Comment by imnapo** [comment] 2019-05-15 13:47
Hi, You should implement **CNRichTextView**  inside a **ScrollView**. 

```
<View style={{flex: 1}}>
 <ScrollView contentContainerStyle={{flexGrow: 1}}>
  <CNRichTextView
    style={{flex: 1}}
    text={this.state.text} />
 </ScrollView>
</View>
```

**Comment by imnapo** [comment] 2019-06-03 11:17
I’m going to close this for now. Feel free to reopen, if the problem is not solved.

**Closed by imnapo** 2019-06-03 11:17 UTC
